image: golang:1.24

stages:
  - test
  - release

test:
  stage: test
  script:
    - go mod download
    - go test -v ./...

release:
  stage: release
  image:
    name: goreleaser/goreleaser:latest
    entrypoint: ['']
  only:
    - tags

  variables:
    GIT_DEPTH: "0"
    GITLAB_TOKEN: $GITLAB_TOKEN

  script:
    # .git существует, но remote может быть пустым → переопределяем
    - git remote set-url origin "$CI_REPOSITORY_URL" || git remote add origin "$CI_REPOSITORY_URL"

    # подгружаем коммит
    - git fetch --depth=1 origin "$CI_COMMIT_SHA"

    # подгружаем теги
    - git fetch --tags origin

    # чекаутим нужный коммит
    - git checkout "$CI_COMMIT_SHA"

    # запускаем goreleaser
    - goreleaser release --clean
