image: golang:1.24

stages:
  - test
  - release

# -------------------------------
#        TEST STAGE
# -------------------------------
test:
  stage: test
  script:
    - go mod download
    - go test -v ./...

# -------------------------------
#        RELEASE STAGE
# -------------------------------
release:
  stage: release
  image:
    name: goreleaser/goreleaser:latest
    entrypoint: ['']
  only:
    - tags

  variables:
    # Полное клонирование репо (передаётся runner-ом, но не контейнеру!)
    GIT_DEPTH: "0"

    # Токен GitLab для публикации релиза
    GITLAB_TOKEN: $GITLAB_TOKEN

  script:
    # -----------------------------------------
    # ВОССТАНАВЛИВАЕМ GIT ВНУТРИ КОНТЕЙНЕРА!
    # (это решает твою проблему repo= и 401)
    # -----------------------------------------

    # создаём новый git репозиторий
    - git init

    # добавляем remote origin
    - git remote add origin "$CI_REPOSITORY_URL"

    # скачиваем нужный коммит
    - git fetch --depth=1 origin "$CI_COMMIT_SHA"

    # скачиваем теги (goreleaser их использует!)
    - git fetch --tags origin

    # чекаутим коммит, на котором запущен pipeline
    - git checkout "$CI_COMMIT_SHA"

    # -----------------------------------------
    # Запускаем GORELEASER
    # -----------------------------------------
    - goreleaser release --clean
