version: 2

project_name: terraform-provider-hostinger

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
  gitlab:
    # Используем use_package_registry: false если нужно (по умолчанию true)
    # Но для идентификации репозитория нужны owner/name.
    # Если вы хотите использовать ID, часто это делается через owner.
    # Однако, я пишу то, что вы прислали:
    project_id: "{{ .Env.CI_PROJECT_ID }}"
  draft: false
  prerelease: auto
